FROM golang:1.18-alpine as builder
RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /go/src/github.com/cecobask/ocd-tracker-api
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o /go/bin/ocd-tracker-api

FROM gcr.io/distroless/static-debian11
EXPOSE 8080 40000
COPY --from=builder /go/bin/ocd-tracker-api .
COPY --from=builder /go/bin/dlv .
COPY --from=builder /go/src/github.com/cecobask/ocd-tracker-api/internal/db/postgres/migration migration

ENTRYPOINT ["./dlv", "--listen=:40000", "--headless", "--api-version=2", "--accept-multiclient", "exec", "./ocd-tracker-api"]