version: "3.8"
services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE