version: "3.8"
services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    env_file:
      - .env
    volumes:
      - ${SERVICE_ACCOUNT_FILE}:/tmp/keys/serviceAccountKey.json:ro
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE